---
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'examples/**'
  - '**/*.d.ts'
  - 'coverage/**'

engines:
  eslint:
    enabled: true
    engine_version: 9

  complexity:
    enabled: true
    exclude_paths:
      - 'test/**'

  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'

  metrics:
    enabled: true
    exclude_paths:
      - 'test/**'

  coverage:
    enabled: true
    exclude_paths:
      - 'test/**'
