---
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'examples/**'
  - '**/*.d.ts'
  - 'coverage/**'
  - 'eslint.config.js'  # Exclude the flat config file that's causing issues

engines:
  eslint:
    enabled: false  # Explicitly disabled due to flat config compatibility issues
  
  # Use other engines for code quality analysis
  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'
  metrics:
    enabled: true
  coverage:
    enabled: false  # We handle coverage separately via CI
