---
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'examples/**'
  - '**/*.d.ts'
  - 'coverage/**'

engines:
  eslint:
    enabled: true
    # Use legacy .eslintrc.js for Codacy compatibility
    exclude_paths:
      - 'eslint.config.js'  # Exclude flat config to force legacy config usage
      
  duplication:
    enabled: true
    exclude_paths:
      - 'test/**'
      
  metrics:
    enabled: true
    
  coverage:
    enabled: false
