---
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'examples/**'
  - '**/*.d.ts'
  - 'coverage/**'

engines:
  eslint:
    enabled: false  # Disabled due to flat config compatibility issues with Codacy ESLint 9
  
  # Codacy will still analyze complexity and other metrics without ESLint
  duplication:
    enabled: true
  metrics:
    enabled: true
