---
exclude_paths:
  - 'node_modules/**'
  - 'dist/**'
  - '.git/**'
  - 'examples/**'
  - '**/*.d.ts'
  - 'coverage/**'

engines:
  eslint-8:
    enabled: false

  eslint-9:
    enabled: true
    configuration_file: eslint.minimal.config.js

  markdownlint:
    enabled: true

  metrics:
    enabled: true
    exclude_paths:
      - 'test/**'

  coverage:
    enabled: true
    exclude_paths:
      - 'test/**'
